### ISSUE TITLE
Migrate to Nextclade v3

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/nipah#4]
[Migration to Nextclade v3 guide](https://docs.nextstrain.org/projects/nextclade/en/stable/user/migration-v3.html) for reference.

## TODOs

- [x] rename `nextalign` to `nextclade` in [phylogenetic/defaults/config.yaml](https://github.com/nextstrain/nipah/blob/a4be47f9ae11c02f26834572a6bbe6ed009dd6a1/phylogenetic/defaults/config.yaml#L18)
- [x] update [nextalign rule in prepare_sequences.smk](https://github.com/nextstrain/nipah/blob/a4be47f9ae11c02f26834572a6bbe6ed009dd6a1/phylogenetic/rules/prepare_sequences.smk#L87-L101)
- [x] update gff to produce valid output using Nextclade v3
    - [x] use `CDS` instead of `gene`
    - [x] update `Name=...` annotations to produce the exact translation files needed by augur ancestral
    - [x] drop `Parent=gene-Nvgp\d;` annotations due to errors about not finding the parent, and since this annotation is not relevant for the output files
