### ISSUE TITLE
Catch-all task list to fine-tune staged phylogenetic trees

### ISSUE THREAD

**Issue by j23414** [nextstrain/nipah#6]
### Context

The nipah pathogen pipeline is automated and will be automatically deployed to a staged site for initial fine-tuning.

* https://next.nextstrain.org/staging/nipah/all
* https://next.nextstrain.org/staging/nipah/human
* https://next.nextstrain.org/staging/nipah/I
* https://next.nextstrain.org/staging/nipah/II

This issue is a temporary catch-all for remaining tasks before pushing the trees to the live site. 

### TODO's

Feel free to edit and add to this list directly:

* [x] Add a reasonable `description.md` to phylogenetic workflow
* [x] Update the auspice_config.json header to point at this repository
* [ ] Document or revisit the subsampling parameters for the phylogenetic tree
* [x] Instead of `builds/{build}`, use `results/{build}` to align with our pathogen-repo-guide
